################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++M_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
CCM_UPPER_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
CXXM_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C++M_UPPER_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_UPPER_DEPS := 
C++M_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
CXXM_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
SREC := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
CCM_DEPS := 
P_UPPER_DEPS := 
CXXM_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CCM_UPPER_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_drw \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_mipi_dsi \
ra/fsp/src/r_mipi_phy \
ra/fsp/src/rm_freertos_port \
ra/tes/dave2d/src \
ra_gen \
src/display/dsi \
src/display \
src/display/lvgl/src/core \
src/display/lvgl/src/display \
src/display/lvgl/src/draw \
src/display/lvgl/src/draw/nxp/pxp \
src/display/lvgl/src/draw/nxp/vglite \
src/display/lvgl/src/draw/renesas/dave2d \
src/display/lvgl/src/draw/sdl \
src/display/lvgl/src/draw/sw/blend/helium \
src/display/lvgl/src/draw/sw/blend \
src/display/lvgl/src/draw/sw/blend/neon \
src/display/lvgl/src/draw/sw \
src/display/lvgl/src/draw/vg_lite \
src/display/lvgl/src/drivers/display/drm \
src/display/lvgl/src/drivers/display/fb \
src/display/lvgl/src/drivers/display/ili9341 \
src/display/lvgl/src/drivers/display/lcd \
src/display/lvgl/src/drivers/display/renesas_glcdc \
src/display/lvgl/src/drivers/display/st7735 \
src/display/lvgl/src/drivers/display/st7789 \
src/display/lvgl/src/drivers/display/st7796 \
src/display/lvgl/src/drivers/display/tft_espi \
src/display/lvgl/src/drivers/evdev \
src/display/lvgl/src/drivers/glfw \
src/display/lvgl/src/drivers/libinput \
src/display/lvgl/src/drivers/nuttx \
src/display/lvgl/src/drivers/sdl \
src/display/lvgl/src/drivers/windows \
src/display/lvgl/src/drivers/x11 \
src/display/lvgl/src/font \
src/display/lvgl/src/indev \
src/display/lvgl/src/layouts/flex \
src/display/lvgl/src/layouts/grid \
src/display/lvgl/src/layouts \
src/display/lvgl/src/libs/barcode \
src/display/lvgl/src/libs/bin_decoder \
src/display/lvgl/src/libs/bmp \
src/display/lvgl/src/libs/ffmpeg \
src/display/lvgl/src/libs/freetype \
src/display/lvgl/src/libs/fsdrv \
src/display/lvgl/src/libs/gif \
src/display/lvgl/src/libs/libjpeg_turbo \
src/display/lvgl/src/libs/libpng \
src/display/lvgl/src/libs/lodepng \
src/display/lvgl/src/libs/lz4 \
src/display/lvgl/src/libs/qrcode \
src/display/lvgl/src/libs/rle \
src/display/lvgl/src/libs/rlottie \
src/display/lvgl/src/libs/thorvg \
src/display/lvgl/src/libs/tiny_ttf \
src/display/lvgl/src/libs/tjpgd \
src/display/lvgl/src \
src/display/lvgl/src/misc/cache \
src/display/lvgl/src/misc \
src/display/lvgl/src/osal \
src/display/lvgl/src/others/file_explorer \
src/display/lvgl/src/others/fragment \
src/display/lvgl/src/others/gridnav \
src/display/lvgl/src/others/ime \
src/display/lvgl/src/others/imgfont \
src/display/lvgl/src/others/monkey \
src/display/lvgl/src/others/observer \
src/display/lvgl/src/others/snapshot \
src/display/lvgl/src/others/sysmon \
src/display/lvgl/src/others/vg_lite_tvg \
src/display/lvgl/src/stdlib/builtin \
src/display/lvgl/src/stdlib/clib \
src/display/lvgl/src/stdlib \
src/display/lvgl/src/stdlib/micropython \
src/display/lvgl/src/stdlib/rtthread \
src/display/lvgl/src/themes/default \
src/display/lvgl/src/themes \
src/display/lvgl/src/themes/mono \
src/display/lvgl/src/themes/simple \
src/display/lvgl/src/tick \
src/display/lvgl/src/widgets/animimage \
src/display/lvgl/src/widgets/arc \
src/display/lvgl/src/widgets/bar \
src/display/lvgl/src/widgets/button \
src/display/lvgl/src/widgets/buttonmatrix \
src/display/lvgl/src/widgets/calendar \
src/display/lvgl/src/widgets/canvas \
src/display/lvgl/src/widgets/chart \
src/display/lvgl/src/widgets/checkbox \
src/display/lvgl/src/widgets/dropdown \
src/display/lvgl/src/widgets/image \
src/display/lvgl/src/widgets/imagebutton \
src/display/lvgl/src/widgets/keyboard \
src/display/lvgl/src/widgets/label \
src/display/lvgl/src/widgets/led \
src/display/lvgl/src/widgets/line \
src/display/lvgl/src/widgets/list \
src/display/lvgl/src/widgets/lottie \
src/display/lvgl/src/widgets/menu \
src/display/lvgl/src/widgets/msgbox \
src/display/lvgl/src/widgets/objx_templ \
src/display/lvgl/src/widgets/property \
src/display/lvgl/src/widgets/roller \
src/display/lvgl/src/widgets/scale \
src/display/lvgl/src/widgets/slider \
src/display/lvgl/src/widgets/span \
src/display/lvgl/src/widgets/spinbox \
src/display/lvgl/src/widgets/spinner \
src/display/lvgl/src/widgets/switch \
src/display/lvgl/src/widgets/table \
src/display/lvgl/src/widgets/tabview \
src/display/lvgl/src/widgets/textarea \
src/display/lvgl/src/widgets/tileview \
src/display/lvgl/src/widgets/win \
src/display/touch \
src \

